import Header from '@/components/ui/header/header';
import FramerMotionWrapper from '@/components/wrapper/framer-motion-wrapper';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header></Header>
      <FramerMotionWrapper>{children}</FramerMotionWrapper>
    </>
  );
}
