import { ComingFromTopVariant } from '@/components/framer-motion/div-variants';
import DivWrapper from '@/components/framer-motion/div-wrapper';
import Footer from '@/components/ui/footer/footer';
import FooterContent from '@/components/ui/footer/footer-content';
import Header from '@/components/ui/header/header';
import HeaderWrapper from '@/components/ui/header/header-wrapper';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <DivWrapper variant={ComingFromTopVariant}>
        <HeaderWrapper>
          <Header></Header>
        </HeaderWrapper>{' '}
      </DivWrapper>
      <>{children}</>

      <Footer>
        <FooterContent></FooterContent>
      </Footer>
    </>
  );
}
